### ISSUE TITLE
Maximum 10 results fetched from database 

### ISSUE THREAD

**Issue by akshatism** [jonaprieto/flask-ponywhoosh#26]
'cant_results' is more than 10 but still 'results' fetches only 10 results from the database. What configuration should I change to increase this number to show more than 10 in the corresponding UI?

**Comment by jonaprieto** [comment]
@akshatism did you figure it out? At the moment, I'm not able to do the support you need. If you could
help contributing solving your issue, it'll be nice.

**Comment by jonaprieto** [comment]
Closed. I couldn't reproduce it, please open it again if you can so.
